---
version: 2
jobs:
  build:
    working_directory: ~/geoportal
    docker:
      # The primary container is an instance of the first list image listed. Your build commands run in this container.
      - image: circleci/ruby:2.6.1-node-browsers
        environment:
          RAILS_ENV: test
          geoportal_DB_HOST: localhost
          geoportal_DB_USERNAME: geoblacklight
    steps:
      - checkout
      # Restore Cached Dependencies
      - type: cache-restore
        name: Restore bundle cache
        key: geoportal-{{ checksum "Gemfile.lock" }}
      # Bundle install dependencies
      - run: gem install bundler:2.0.1
      - run: bundle update --bundler
      - run: bundle install --path vendor/bundle
      - run: bundle exec rake db:migrate
      - run: bundle exec rake ci
      # Cache Dependencies
      - type: cache-save
        name: Store bundle cache
        key: geoportal-{{ checksum "Gemfile.lock" }}
        paths:
          - vendor/bundle
workflows:
  version: 2
  build_accept_deploy:
    jobs:
      - build
