# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'http://geoblacklight.org/images/geoblacklight-logo.png'

#BING_SITE_VERIFICATION: '4E61263975C6ABBF2ECE5A8CA5E592B7'

# Carto OneClick Service https://carto.com/engine/open-in-carto/
CARTO_ONECLICK_LINK: 'http://oneclick.carto.com/'

# ArcGIS Online Base URL
ARCGIS_BASE_URL: 'https://www.arcgis.com/home/webmap/viewer.html'

EMAIL_TO: 'fake-email@example.com'

#Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'

# The bq boost value for spatial search matches within a bounding box
BBOX_WITHIN_BOOST: '10'

# The bf boost value for overlap ratio
OVERLAP_RATIO_BOOST: '10'

#Solr field mappings
FIELDS:
  :FILE_FORMAT: 'dc_format_s'
  :GEOMETRY: 'solr_geom'
  :WXS_IDENTIFIER: 'layer_id_s'
  :RIGHTS: 'dc_rights_s'
  :PROVENANCE: 'dct_provenance_s'
  :GEOM_TYPE: 'layer_geom_type_s'
  :SPATIAL_COVERAGE: 'dct_spatial_sm'
  :SUBJECT: 'dc_subject_sm'
  :REFERENCES: 'dct_references_s'
  :YEAR: 'dct_temporal_sm'
  :CREATOR: 'dc_creator_sm'
  :DESCRIPTION: 'dc_description_s'
  :PUBLISHER: 'dc_publisher_s'
  :PART_OF: 'dct_isPartOf_sm'
  :TEMPORAL: 'dct_temporal_sm'
  :TITLE: 'dc_title_s'
  :SOURCE: 'dc_source_sm'

GEOMONITOR_TOLERANCE: 0.8
#GOOGLE_ANALYTICS_ID: 'UA-XXXXX-X'
#GOOGLE_SITE_VERIFICATION: 'I1DQ46tUnPOrYpnhDUsy5tOL22oywWb2LyUTwT8M-HU'
HOSTNAME: 'HOST'
HOST_URL: 'http://geo.btaa.org'
INSTITUTION: 'University of Minnesota'

INSTITUTION_LOCAL_NAME: 'Minnesota'
INSTITUTION_GEOSERVER_URL: 'https://geoserver.princeton.edu'
PROXY_GEOSERVER_URL: 'http://localhost:3000'
PROXY_GEOSERVER_AUTH: 'Basic base64encodedusername:password'

GBLSI_THUMBNAIL_FIELD: 'b1g_image_ss'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'fgdc'
  - 'iso19139'
  - 'mods'
  - 'html'

#NEWRELIC_APP_NAME: 'should be specific to stage and prod'
#NEWRELIC_LICENSE_KEY: 'this is private'

PROXY_URL: 'http://www.example.com/restricted'

RESTRICTED_URL: 'http://www.example-services.com'

#SQUASH_API_HOST: 'http://squash-host.example.com'
#SQUASH_API_KEY: 'squash-api-key'
#SQUASH_DISABLE: <%= (Rails.env.development? || Rails.env.test?) %>

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'wfs'
  - 'iiif'
  - 'feature_layer'
  - 'tiled_map_layer'
  - 'dynamic_map_layer'
  - 'image_map_layer'

WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'

# Settings for leaflet
OPACITY_CONTROL: &opacity_control
  CONTROLS:
    - 'Opacity'

LEAFLET:
  MAP:
  LAYERS:
    DETECT_RETINA: true
    INDEX:
      DEFAULT: &default
        color: "#1eb300"
        weight: "1"
        radius: "4"
      UNAVAILABLE:
        <<: *default
        color: "#b3001e"
      SELECTED:
        <<: *default
        color: "#006bde"
  VIEWERS:
    DOWNLOAD:
      CONTROLS:
    IIIF:
      CONTROLS:
        - 'Fullscreen'
    WMS:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    TILEDMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    FEATURELAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    DYNAMICMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    IMAGEMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'

B1G_HELP:
  download:
    link_text: Static Image
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - Static Image
    popover_text: A downloadable image.
  dynamic_map_layer:
    link_text: ArcGIS Dynamic Map Layer
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - ArcGIS Dynamic Map Layer
    popover_text: An ArcGIS Dynamic Map Layer is based on vector data. (points, lines, and polygons). Map image layers are dynamically rendered image tiles. Click on a feature to view attribute information.
  feature_layer:
    link_text: ArcGIS Feature Layer
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - ArcGIS Feature Layer
    popover_text: An ArcGIS Feature Layer Service displays vector data (points, lines, and polygons) as individual or collected features. Click on a feature to view attribute information.
  iiif:
    link_text: IIIF Service
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - IIIF Service
    popover_text: The International Image Interoperability Framework (IIIF) web service API displays an image from a server. This image can be panned and zoomed.
  iiif_manifest:
    link_text: IIIF Service
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - IIIF Service
    popover_text: The International Image Interoperability Framework (IIIF) web service API displays an image from a server. This image can be panned and zoomed.
  image_map_layer:
    link_text: ArcGIS Image Map Layer
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - ArcGIS Image Map Layer
    popover_text: An ArcGIS Image Map Layer displays raster data (a grid of cells used to store imagery).
  index_map:
    link_text: Index Map
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - Index Map
    popover_text: Index maps are a type of finding aid that allows a user to use a map to select a specific item within a set. Click on a feature to view individual map pages.
  tiled_map_layer:
    link_text: ArcGIS Tiled Map Layer
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - ArcGIS Tiled Map Layer
    popover_text: An ArcGIS Tiled Map Layer Service displays set of web-accessible tiles that reside on a server.
  wms:
    link_text: Web Map Service (WMS)
    link_href: https://btaagdp.org/help/web-services
    popover_title: Help - Web Map Service (WMS)
    popover_text: A Web Map Service displays a geospatial dataset as map images.
