# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'http://geoblacklight.org/images/geoblacklight-logo.png'

#BING_SITE_VERIFICATION: '4E61263975C6ABBF2ECE5A8CA5E592B7'

# Carto OneClick Service https://carto.com/engine/open-in-carto/
CARTO_ONECLICK_LINK: 'http://oneclick.carto.com/'

# ArcGIS Online Base URL
ARCGIS_BASE_URL: 'https://www.arcgis.com/home/webmap/viewer.html'

EMAIL_TO: 'fake-email@example.com'

#Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'

# The bq boost value for spatial search matches within a bounding box
BBOX_WITHIN_BOOST: '10'

# The bf boost value for overlap ratio
OVERLAP_RATIO_BOOST: '10'

#Solr field mappings
FIELDS:
  :CREATOR: 'dct_creator_sm'
  :DATE_RANGE: 'gbl_dateRange_drsim'
  :DESCRIPTION: 'dct_description_sm'
  :FILE_FORMAT: 'dct_format_s'
  :GEOM_TYPE: 'gbl_resourceType_sm'
  :GEOMETRY: 'locn_geometry'
  :IDENTIFIER: 'dct_identifier_sm'
  :ISSUED: 'dct_issued_s'
  :LANGUAGE: 'dct_language_sm'
  :LAYER_MODIFIED: 'gbl_mdModified_dt'
  :OVERLAP_FIELD: 'solr_bboxtype'
  :PART_OF: 'dct_isPartOf_sm'
  :PUBLISHER: 'dct_publisher_sm'
  :PROVENANCE: 'schema_provider_s'
  :REFERENCES: 'dct_references_s'
  :RIGHTS: 'dct_accessRights_s'
  :SPATIAL_COVERAGE: 'dct_spatial_sm'
  :SUBJECT: 'dct_subject_sm'
  :SOURCE: 'dct_source_sm'
  :SUPPRESSED: 'gbl_suppressed_b'
  :TEMPORAL: 'dct_temporal_sm'
  :TITLE: 'dct_title_s'
  :TYPE: 'dct_type_s'
  :UNIQUE_KEY: 'geomg_id_s'
  :WXS_IDENTIFIER: 'gbl_wxsIdentifier_s'
  :YEAR: 'gbl_indexYear_im'

GEOMONITOR_TOLERANCE: 0.8
#GOOGLE_ANALYTICS_ID: 'UA-XXXXX-X'
#GOOGLE_SITE_VERIFICATION: 'I1DQ46tUnPOrYpnhDUsy5tOL22oywWb2LyUTwT8M-HU'
HOSTNAME: 'HOST'
HOST_URL: 'http://geo.btaa.org'
INSTITUTION: 'University of Minnesota'

INSTITUTION_LOCAL_NAME: 'Minnesota'
INSTITUTION_GEOSERVER_URL: 'https://geoserver.princeton.edu'
PROXY_GEOSERVER_URL: 'http://localhost:3000'
PROXY_GEOSERVER_AUTH: 'Basic base64encodedusername:password'

GBLSI_THUMBNAIL_FIELD: 'b1g_image_ss'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'fgdc'
  - 'iso19139'
  - 'mods'
  - 'html'

#NEWRELIC_APP_NAME: 'should be specific to stage and prod'
#NEWRELIC_LICENSE_KEY: 'this is private'

PROXY_URL: 'http://www.example.com/restricted'

RESTRICTED_URL: 'http://www.example-services.com'

#SQUASH_API_HOST: 'http://squash-host.example.com'
#SQUASH_API_KEY: 'squash-api-key'
#SQUASH_DISABLE: <%= (Rails.env.development? || Rails.env.test?) %>

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'wfs'
  - 'iiif'
  - 'feature_layer'
  - 'tiled_map_layer'
  - 'dynamic_map_layer'
  - 'image_map_layer'

WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'

# Settings for leaflet
OPACITY_CONTROL: &opacity_control
  CONTROLS:
    - 'Opacity'

LEAFLET:
  MAP:
  LAYERS:
    DETECT_RETINA: true
    INDEX:
      DEFAULT: &default
        color: "#1eb300"
        weight: "1"
        radius: "4"
      UNAVAILABLE:
        <<: *default
        color: "#b3001e"
      SELECTED:
        <<: *default
        color: "#006bde"
  VIEWERS:
    DOWNLOAD:
      CONTROLS:
    IIIF:
      CONTROLS:
        - 'Fullscreen'
    WMS:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    TILEDMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    FEATURELAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    DYNAMICMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    IMAGEMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'

# Toggle the help text feature that offers users context
HELP_TEXT:
  viewer_protocol:
      - 'b1g_image'
      - 'download'
      - 'dynamic_map_layer'
      - 'feature_layer'
      - 'iiif'
      - 'iiif_manifest'
      - 'image_map_layer'
      - 'index_map'
      - 'tiled_map_layer'
      - 'wms'
      - 'oembed'
