# Configurable Logo Used for CartoDB export
APPLICATION_LOGO_URL: 'http://geoblacklight.org/images/geoblacklight-logo.png'

#BING_SITE_VERIFICATION: '4E61263975C6ABBF2ECE5A8CA5E592B7'

# Carto OneClick Service https://carto.com/engine/open-in-carto/
CARTO_ONECLICK_LINK: 'http://oneclick.carto.com/'

EMAIL_TO: 'fake-email@example.com'

#Main Solr geometry field used for spatial search and bounding box. Should be type 'rpt'
GEOMETRY_FIELD: 'solr_geom'

# The bq boost value for spatial search matches within a bounding box
# BBOX_WITHIN_BOOST: '10'

#Solr field mappings
FIELDS:
  :FILE_FORMAT: 'dc_format_s'
  :GEOMETRY: 'solr_geom'
  :WXS_IDENTIFIER: 'layer_id_s'
  :RIGHTS: 'dc_rights_s'
  :PROVENANCE: 'dct_provenance_s'
  :GEOM_TYPE: 'layer_geom_type_s'
  :SPATIAL_COVERAGE: 'dct_spatial_sm'
  :SUBJECT: 'dc_subject_sm'
  :REFERENCES: 'dct_references_s'
  :YEAR: 'dct_temporal_sm'
  :CREATOR: 'dc_creator_sm'
  :DESCRIPTION: 'dc_description_s'
  :PUBLISHER: 'dc_publisher_s'
  :PART_OF: 'dct_isPartOf_sm'
  :TEMPORAL: 'dct_temporal_sm'
  :TITLE: 'dc_title_s'
  :SOURCE: 'dc_source_sm'

GEOMONITOR_TOLERANCE: 0.8
#GOOGLE_ANALYTICS_ID: 'UA-XXXXX-X'
#GOOGLE_SITE_VERIFICATION: 'I1DQ46tUnPOrYpnhDUsy5tOL22oywWb2LyUTwT8M-HU'
HOSTNAME: 'HOST'
HOST_URL: 'http://geo.btaa.org'
INSTITUTION: 'University of Minnesota'

INSTITUTION_LOCAL_NAME: 'Minnesota'
INSTITUTION_GEOSERVER_URL: 'https://geoserver.princeton.edu'
PROXY_GEOSERVER_URL: 'http://localhost:3000'
PROXY_GEOSERVER_AUTH: 'Basic base64encodedusername:password'

GBLSI_THUMBNAIL_FIELD: 'b1g_image_ss'

# Metadata shown in tool panel
METADATA_SHOWN:
  - 'fgdc'
  - 'iso19139'
  - 'mods'
  - 'html'

#NEWRELIC_APP_NAME: 'should be specific to stage and prod'
#NEWRELIC_LICENSE_KEY: 'this is private'

PROXY_URL: 'http://www.example.com/restricted'

RESTRICTED_URL: 'http://www.example-services.com'

#SQUASH_API_HOST: 'http://squash-host.example.com'
#SQUASH_API_KEY: 'squash-api-key'
#SQUASH_DISABLE: <%= (Rails.env.development? || Rails.env.test?) %>

# (For external Download) timeout and open_timeout parameters for Faraday
TIMEOUT_DOWNLOAD: 16

# (For WMS inspection) timeout and open_timeout parameters for Faraday
TIMEOUT_WMS: 4

# Web services shown in tool panel
WEBSERVICES_SHOWN:
  - 'wms'
  - 'wfs'
  - 'iiif'
  - 'feature_layer'
  - 'tiled_map_layer'
  - 'dynamic_map_layer'
  - 'image_map_layer'

WMS_PARAMS:
  :SERVICE: 'WMS'
  :VERSION: '1.1.1'
  :REQUEST: 'GetFeatureInfo'
  :STYLES: ''
  :SRS: 'EPSG:4326'
  :EXCEPTIONS: 'application/json'
  :INFO_FORMAT: 'text/html'

# The bf boost value for overlap ratio
OVERLAP_RATIO_BOOST: '2'

# Settings for leaflet
OPACITY_CONTROL: &opacity_control
  CONTROLS:
    - 'Opacity'

LEAFLET:
  MAP:
  LAYERS:
  VIEWERS:
    DOWNLOAD:
      CONTROLS:
        - 'Fullscreen'
    IIIF:
      CONTROLS:
        - 'Fullscreen'
    WMS:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    TILEDMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    FEATURELAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    DYNAMICMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
    IMAGEMAPLAYER:
      CONTROLS:
        - 'Opacity'
        - 'Fullscreen'
        - 'Layers'
